In [1]:
# Import dependencies
import pandas as pd
import os

In [5]:
# Read in csv
df = pd.read_csv("cumulative.csv")
# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')
# Drop the null rows
df = df.dropna()
df.head()

,rowid,kepid,kepoi_name,kepler_name,koi_disposition,koi_pdisposition,koi_score,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,...,koi_steff_err2,koi_slogg,koi_slogg_err1,koi_slogg_err2,koi_srad,koi_srad_err1,koi_srad_err2,ra,dec,koi_kepmag
0,1,10797460,K00752.01,Kepler-227 b,CONFIRMED,CANDIDATE,1.000,0,0,0,...,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
1,2,10797460,K00752.02,Kepler-227 c,CONFIRMED,CANDIDATE,0.969,0,0,0,...,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
4,5,10854555,K00755.01,Kepler-664 b,CONFIRMED,CANDIDATE,1.000,0,0,0,...,-211.0,4.438,0.070,-0.210,1.046,0.334,-0.133,288.75488,48.226200,15.509
5,6,10872983,K00756.01,Kepler-228 d,CONFIRMED,CANDIDATE,1.000,0,0,0,...,-232.0,4.486,0.054,-0.229,0.972,0.315,-0.105,296.28613,48.224670,15.714
6,7,10872983,K00756.02,Kepler-228 c,CONFIRMED,CANDIDATE,1.000,0,0,0,...,-232.0,4.486,0.054,-0.229,0.972,0.315,-0.105,296.28613,48.224670,15.714

In [6]:
# Set features (x values)
#selected_features = df[['names', 'of', 'selected', 'features', 'here']]

In [7]:
# Create a train test split (koi_disposition to be used as y value)
#X_train.head()

In [8]:
# Scale data

In [9]:
# Train the model
#print(f"Training Data Score: {model2.score(X_train_scaled, y_train)}")
#print(f"Testing Data Score: {model2.score(X_test_scaled, y_test)}")

In [10]:
# Use GridSearchCV to tune the model's parameters
# Create the GridSearchCV model

In [11]:
# Train the model with GridSearch
#print(grid2.best_params_)
#print(grid2.best_score_)

In [ ]:
# Save the model
#import joblib
#filename = 'Chelsea.sav'
#joblib.dump(your_model, filename)